### ISSUE TITLE
escape "\" command not executing properly

### ISSUE THREAD

**Issue by Ryan-C-Lee** [looker/looker-slackbot#23]
command = `/looker am customer\, inc\.`

Returns no results. When drilling into the link, the filter value is being populated with: 

`customer,inc\. `

(missing the space after the comma, and not recognizing the second escape for the period).

**Comment by wilg** [comment]
This is actually working properly, it's just the wrong advanced syntax.

This command will work:

`/looker am "customer, inc."`
