### ISSUE TITLE
https: path for S3 png fails to display in slack

### ISSUE THREAD

**Issue by Benyuel** [looker/looker-slackbot#30]
One possible fix is changing Line 65 success url to 

> http

 in lib/bot.coffee

**Comment by wilg** [comment]
@Benyuel Could you describe more about the issue you're encountering? HTTPS should work for S3, and we definitely don't want to use an insecure protocol.

**Comment by Benyuel** [comment]
@wilg Sure. I have not spent a whole lot of time investigating this deeply, but here are my general thoughts/theory on what is happening.
The bot has the image link in S3 as a slack attachment with the general structure 
```javascript
https://mybucket.mydomain.com.s3.amazonaws.com/myObjectKey 
```
The host name component of the URL is mybucket.mydomain.com.s3.amazonaws.com, but the actual server that gets the request is an S3 server whose certificate was issued to *.s3.amazonaws.com. mybucket.mydomain.com.s3.amazonaws.com is not a subdomain of s3.amazonaws.com. A multi-level subdomain – that is, a subdomain that has more than one period in it – is not considered to be a proper subdomain by most clients. So the client will report that the server’s SSL certificate, issued to *.s3.amazonaws.com, does not match the host name of the request, mybucket.mydomain.com.s3.amazonaws.com, and refuse to establish a secure connection.

The same problem occurs when you request the virtual host https URL 
```javascript
https://mybucket.mydomain.com/myObjectKey
```
 The request arrives – after the client discovers that mybucket.mydomain.com is a DNS CNAME alias for mybucket.mydomain.com.s3.amazonaws.com – at an S3 server with an SSL certificate issued to *.s3.amazonaws.com. In this case the host name mybucket.mydomain.com clearly does not match the host name on the certificate, so the secure connection again fails.

All this results in the slack bot making a post with the https S3 file attachment, but the attachment does not show in slack.  It's a blank message from the bot.

Probably a few different ways of dealing with this (haven't tested them all):
1.  Use the http url
2.  Change the structure of the image link in the slack attachment to 
```javascript
https://s3.amazonaws.com/mybucket.mydomain.com/myObjectKey
```
or
```javascript
https://simplebucketname.s3.amazonaws.com/myObjectKey
```javascript
where simplebucketname does not contain any periods
3.  Force your bucket names to be mybucket-mydomain-com (i.e. no periods)

**Comment by wilg** [comment]
Ah – I think it's indeed because your bucket name contains the `.` character. I'll modify it to use the path you mention above.

**Comment by wilg** [comment]
Thank you for the detailed bug report, as well! Very helpful!
