### ISSUE TITLE
Suggest Including S3 Bucket Policy Requirements

### ISSUE THREAD

**Issue by bconneen** [looker/looker-slackbot#37]
Took me quite a bit of tinkering to figure out the correct policies for the S3 Bucket User. I might even be over granting still. The biggest hang up I was having was PutObectAcl.  The errors messages didn't really describe what was missing, so I had to tinker around and check the code. Also might want to mention that you have to turn Static Website hosting on. (common sense, but it could help somebody.)

Here is my current policy, but I think it might more permissive than needed.

"Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],

**Comment by wilg** [comment]
`s3:PutObjectAcl` should be the only policy required as far as I know. You're right we should note this somewhere.

**Comment by jrrbelmont** [comment]
Thanks for the hint! The Static Website part was not obvious to me.

**Comment by wilg** [comment]
Strange, I forgot to mention it above but "Static Website" should *not* need to be enabled for Lookerbot to work.
