### ISSUE TITLE
NodeJS not running

### ISSUE THREAD

**Issue by jeromemyers** [looker/looker-slackbot#39]
I'm attempting to setup the Looker-slackbot.  I have an EC2 instance with nodeJS loaded and the require key values paris in the .env file at the root of the looker-slack repo.  

When attempting to start nodeJS app I'm getting the following errors. Any help on this would be great.

```
[root@lookerbot-01 looker-slackbot]# nf start
[OKAY] Loaded ENV .env File as KEY=VALUE Format
[OKAY] Trimming display Output to 109 Columns

/usr/lib/node_modules/foreman/nf.js:100
      process.setuid(process.env.SUDO_USER);
              ^
TypeError: setuid argument must be a number or a string
    at Command.program.command.usage.option.description.action.command (/usr/lib/node_modules/foreman/nf.js:100:15)
    at Command.<anonymous> (/usr/lib/node_modules/foreman/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib/node_modules/foreman/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/lib/node_modules/foreman/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/usr/lib/node_modules/foreman/nf.js:280:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[root@lookerbot-01 looker-slackbot]# 
```

**Comment by wilg** [comment]
Hmm... strange. Seems like it pertains to this node-foreman issue: https://github.com/strongloop/node-foreman/issues/70

Some options:

- Try running with sudo (`sudo nf start`)
- Are you running as the root user? Running as a non-priveleged user may be the issue
- Upgrading to foreman `v.2.0.0-0` may help due to this patch: https://github.com/strongloop/node-foreman/commit/723d395e8173aec07e6c1d342896a6bdf52609bc
- Try running without Foreman
     - This means you need to put each environment variable in the command line like `VAR1=value VAR2=value2 npm start`

**Comment by jeromemyers** [comment]
Thanks, I attempted to start the application using sudo (sudo nf start) and
without Foreman.  They both seem to be stuck at the same place.

Here is the stack trace

[OKAY] Loaded ENV .env File as KEY=VALUE Format
[OKAY] Trimming display Output to 153 Columns
10:59:33 web.1 |  > looker-slackbot@0.0.3 start /opt/looker-slackbot
10:59:33 web.1 |  > coffee lib/bot.coffee
10:59:34 web.1 |  Using Looker information specified in individual
environment variables.
10:59:34 web.1 |  info: ** No persistent storage method specified! Data may
be lost when process shuts down.
10:59:34 web.1 |  info: ** Setting up custom handlers for processing Slack
messages
10:59:34 web.1 |  info: ** API CALL: https://slack.com/api/rtm.start
10:59:34 web.1 |  info: ** API CALL: https://slack.com/api/team.info
10:59:34 web.1 |  info: ** Starting webserver on port 5000
10:59:34 web.1 |  info: ** Serving webhook endpoints for Slash commands and
outgoing webhooks at: http://MY_HOST:5000/slack/receive
10:59:35 web.1 |  info: Warning: using temporary storage. Data will be lost
when process restarts.
10:59:35 web.1 |  Saved the team information...
10:59:35 web.1 |  Updated API token for
https://ifactorconsulting.looker.com:19999/api/3.0
10:59:35 web.1 |  notice: ** BOT ID: looker ...attempting to connect to RTM!

**Comment by wilg** [comment]
That doesn't look like an error message, I believe that's just the bot running. It should be listed as "available" in slack and you should be able to interact with it at this point.

**Comment by jeromemyers** [comment]
Your right, thanks for the help.

On Tue, Apr 12, 2016 at 11:30 AM, Wil Gieseler <notifications@github.com>
wrote:

> That doesn't look like an error message, I believe that's just the bot
> running. It should be listed as "available" in slack and you should be able
> to interact with it at this point.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/looker/looker-slackbot/issues/39#issuecomment-209043663>
>



-- 
*Jerome Myers*
Customer Solutions Engineer
iFactor, A KUBRA Company
480 . 532 . 4443 {Cell}
jerome.myers@kubra.com

**Comment by wilg** [comment]
Of course! Let us know if you run into any other issues.
