### ISSUE TITLE
Error: 413 "Payload Too Large" for Scheduled Webhook Payloads

### ISSUE THREAD

**Issue by dataist** [looker/looker-slackbot#59]
Hey Looker-Slackbot team, 

I've used the Heroku button deploy to launch slack bot (great experience!). I've gotten everything working however when I schedule a dashboard to be delivered to a lookerbots webhook endpoint for channels. I get an email error, `Error: 413 "Payload Too Large` instead of a slack post. Doing some digging it looks like maybe the default node body parser defaults may need to be changed ([example](http://stackoverflow.com/questions/19917401/error-request-entity-too-large)).

Thanks!

Jesse

**Comment by wilg** [comment]
Scheduling dashboards isn't supported at the moment so gonna close in favor of #58 but this is a problem we'll have to fix to make that work obviously.
