### ISSUE TITLE
CoffeeScript must be installed globally

### ISSUE THREAD

**Issue by alexbao** [looker/looker-slackbot#62]
Error report attached as below:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.3.0
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle looker-slackbot@0.0.7~prestart: looker-slackbot@0.0.7
6 silly lifecycle looker-slackbot@0.0.7~prestart: no script for prestart, continuing
7 info lifecycle looker-slackbot@0.0.7~start: looker-slackbot@0.0.7
8 verbose lifecycle looker-slackbot@0.0.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle looker-slackbot@0.0.7~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Alex/Develop/src/github.com/alexbao/looker-slackbot/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/Alex/Develop/bin:/usr/local/opt/go/libexec/bin:/Users/Alex/Develop/tools:/Users/Alex/Develop/src/github.com/goforward/infrastructure/scripts
10 verbose lifecycle looker-slackbot@0.0.7~start: CWD: /Users/Alex/Develop/src/github.com/alexbao/looker-slackbot
11 silly lifecycle looker-slackbot@0.0.7~start: Args: [ '-c', 'coffee lib/bot.coffee' ]
12 silly lifecycle looker-slackbot@0.0.7~start: Returned: code: 1  signal: null
13 info lifecycle looker-slackbot@0.0.7~start: Failed to exec start script
14 verbose stack Error: looker-slackbot@0.0.7 start: `coffee lib/bot.coffee`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid looker-slackbot@0.0.7
16 verbose cwd /Users/Alex/Develop/src/github.com/alexbao/looker-slackbot
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.10.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error looker-slackbot@0.0.7 start: `coffee lib/bot.coffee`
23 error Exit status 1
24 error Failed at the looker-slackbot@0.0.7 start script 'coffee lib/bot.coffee'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the looker-slackbot package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     coffee lib/bot.coffee
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs looker-slackbot
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls looker-slackbot
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by wilg** [comment]
Hmm, maybe we don't deal well with CoffeeScript not already being installed. Try running `npm install -g coffee-script` first.

**Comment by alexbao** [comment]
it worked, thanks @wilg !

**Comment by wilg** [comment]
Reopening as I think this shouldn't be required

**Comment by wilg** [comment]
May be fixed when https://github.com/looker/looker-slackbot/issues/60 is closed
