### ISSUE TITLE
Could not schedule look to slack channel

### ISSUE THREAD

**Issue by alexbao** [looker/looker-slackbot#64]
I followed the steps in
https://github.com/looker/looker-slackbot#scheduling-data-to-slack
to set up the webhook, and pretty sure have the LOOKER_WEBHOOK_TOKEN set up with "Outgoing Webhook Token" from Looker admin panel.

I tried to "sent test" of a look (not dashboar) with single big number on the look. The service has the access to the space. No warnings show up, and it says "On its way!". Didn't see the msg in slack channel (server to slack is working for slash_command already) and no logs from server side.

Is there any place I can look into to debug? Thanks!

**Comment by alexbao** [comment]
thanks @wilg!

y, I saw some logs from looker :

> Sending webhook to [URL]/slack/post/channel/s-metrics (Webhook ID: fb65d3424483223b683e0033fdcbc2dc)
Could not send a webhook (Webhook ID: fb65d3424483223b683e0033fdcbc2dc) to [URL]/slack/post/channel/s-metrics

Didn't see anything from the slackbot logs though. Could you instruct anything I should look into further? Thanks!

**Comment by alexbao** [comment]
Here is some more log from looker:

> OpenSSL::SSL::SSLError
Socket closed
org/jruby/ext/openssl/SSLSocket.java:227:in `connect_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:938:in `connect'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'
uri:classloader:/helltool-release-4.8/lib/helltool/models/outgoing_webhook.class:49:in `send!'
uri:classloader:/helltool-release-4.8/lib/helltool/models/outgoing_webhook.class:16:in `send_payload!'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/webhook.class:32:in `block in deliver!'
org/jruby/RubyArray.java:1734:in `each'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/webhook.class:28:in `deliver!'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/deliver.class:57:in `block in deliver'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/deliver.class:52:in `deliver'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/deliver.class:30:in `process_job'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/deliver.class:11:in `block in start'
org/jruby/RubyKernel.java:1296:in `loop'
uri:classloader:/helltool-release-4.8/lib/helltool/scheduler/deliver.class:11:in `block in start'
uri:classloader:/helltool-release-4.8/lib/helltool/immortal_job_pool.class:39:in `block in spawn_thread'
org/jruby/RubyKernel.java:1296:in `loop'
uri:classloader:/helltool-release-4.8/lib/helltool/immortal_job_pool.class:39:in `block in spawn_thread'
uri:classloader:/helltool-release-4.8/lib/helltool/core_ext/thread.class:10:in `block in new'
2017-03-09 19:36:42.167 +0000 [ERROR|00b2c|webhook] :: Error posting to WebHook. No response given.

**Comment by wilg** [comment]
Looks like an SSL connection problem. Some things to check:

- Is your bot host using HTTPS?
- Does your bot host have a valid certificate?
- Does the certificate use SNI (https://en.wikipedia.org/wiki/Server_Name_Indication)? This is the case with some CloudFlare SSL certificates and Looker's webhook system does not currently support SNI.

**Comment by alexbao** [comment]
@wilg thanks for the quick reply!

Seems that's the case, let me check whether I can use the cfs deployment.

**Comment by alexbao** [comment]
Deployed the service to CloudFormation and solved the problem.
Thanks very much @wilg !

**Comment by rsmichaeldunn** [comment]
I feel like there's some context missing here.  @alexbao mentioned *the* cfs deployment.  _What_ cfs deployment is being referred to?  Is there any documentation about setting up looker-slackbot with SSL on EC2?

**Comment by wilg** [comment]
There's no docs specific to looker-slackbot with SSL on EC2, no. Not sure exacrtly what @alexbao's issue was or how it was solved, but the above steps are a good thing to check if you're having similar issues.

**Comment by rsmichaeldunn** [comment]
@wilg is there any configuration that needs to be done to allow the bot to work with SSL, or does that just work with default settings on the bot, as long as there is a cert on the host?

Thanks!

**Comment by wilg** [comment]
@rsmichaeldunn Slack requires that Slash commands (and other potential future types of notifications from Slack _to_ the bot) use SSL with a valid certificate. Looker requires the same for receiving scheduled webhooks and data actions.

The bot doesn't provide an SSL server out-of-the box, it's meant for the SSL to be applied by a proxy (this is how Heroku does it and some of our own internal infrastructure). That's usually the easiest way to apply a cert to the bot.

It's still possible to minimally use the bot without slash commands or scheduling without the bot running as a server publicly accessible to the internet, because it will just open a connection to Slack's RTM API and doesn't need inbound connections for the basic features.
