### ISSUE TITLE
An error has occurred.

### ISSUE THREAD

**Issue by fernavid** [looker/looker-slackbot#65]
Got this when asking for a dashboard that uses a model connected to Athena. Other dashboards work fine. I'm thinking MAYBE it's a permissions issue with the model? Either way maybe a more helpful error message could be produced?

`11:45:55 web.1 |  { message: 'An error has occurred.',
11:45:55 web.1 |    documentation_url: 'http://docs.looker.com/' }`

In the slack chat the bot just edit's it's message to say "An error has occurred".

**Comment by wilg** [comment]
That's true – the bot just relays the error message Looker provides which in this case is basically useless.

Perhaps the Looker logs will have more information.

If it's a permissions issue it may be because the bot user does not have access to that model?

**Comment by fernavid** [comment]
It did indeed turn our to be a permissioning issue. Found out by sudoing as the Looker bot user. Thanks!
