### ISSUE TITLE
Support IAM instance profiles for AWS credentials

### ISSUE THREAD

**Issue by reedloden** [looker/looker-slackbot#75]
The `aws-sdk` for Node.js follows an order when looking for AWS credentials:
https://github.com/aws/aws-sdk-js/blob/4c768539749f4c3056d30a58fa0ddba28df5504c/lib/credentials/credential_provider_chain.js#L119-L133

However, https://github.com/looker/looker-slackbot/blob/9b395f89e6625557bb687dc8a196b97ef384d7b8/lib/bot.coffee#L54 requires that `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environmental variables be used or the S3 bucket code isn't used at all.

This presents a problem, as with IAM instance profile support, those environmental variables need to not exist so that the SDK falls through to checking the EC2 metadata service.

**Comment by wilg** [comment]
Good call, I actually looked at a similar problem for the Google authentication. I think the easiest thing to do here is just switch to checking the presence of `SLACKBOT_S3_BUCKET` to determine if S3 is the desired storage option.

**Comment by reedloden** [comment]
@wilg, good idea. I just submitted #76 for that exact thing, as well as changed it for Azure so all three now use the bucket/container name for whether the storage service should be used.
