### ISSUE TITLE
Restrict responses to full Slack members only

### ISSUE THREAD

**Issue by reedloden** [looker/looker-slackbot#86]
Looker can contain some pretty sensitive information about a company's operations, and a company's Slack instance could contain users who are "guests" (either single or multi-channel). These guests can still talk to `@looker` (via in channel or in DM) currently, causing possible security/privacy issues.

Would be good to have an option that restricts any Lookerbot responses to full members of a Slack instance only.

It took a while to figure out how to differentiate between full vs. guest users, but finally figured out that this information can be gleamed from [`users.info`](https://api.slack.com/methods/users.info) or [`users.list`](https://api.slack.com/methods/users.list) via the `is_restricted` (Multi-Channel Guest) and `is_ultra_restricted` (Single-Channel Guest) boolean attributes.

**Comment by wilg** [comment]
Good call. Implemented!

**Comment by reedloden** [comment]
<3 <3 <3 <3

Can you do a new release?

**Comment by wilg** [comment]
Done: https://github.com/looker/looker-slackbot/releases/tag/0.0.12
